# Generated by Django 4.2.5 on 2023-09-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxyapp', '0002_alter_modelslip_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='modelslip',
        ),
    ]
